AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Relatório Service - Reports Management Microservice'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, staging, prod]
    Description: Environment name

  DatabasePassword:
    Type: String
    NoEcho: true
    Default: dev123456
    Description: Database password

  DatabaseUrlParameter:
    Type: AWS::SSM::Parameter::Value<String>    # ou <SecureString>
    Default: /secret/database_url

Globals:
  Function:
    Runtime: python3.13
    Timeout: 30
    MemorySize: 512
    Environment:
      Variables:
        ENVIRONMENT: !Ref Environment
        LOG_LEVEL: INFO
        DATABASE_URL: !Ref DatabaseUrlParameter
    Tags:
      Service: relatorio    # tag aplicada a todas as Lambdas

Resources:
  # API Gateway explícito para suportar DefaultAuthorizer
  RelatorioApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        DefaultAuthorizer: LambdaAuth
        AddDefaultAuthorizerToCorsPreflight: false
        Authorizers:
          LambdaAuth:
            FunctionArn: !ImportValue
              Fn::Sub: 'AuthFunctionArn'
            Identity:
              Header: Authorization

      Tags:
        Service: relatorio   # tag aplicada ao API Gateway

  # === REPORTS FUNCTIONS ===
  GetRelatoriosFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: handlers.relatorio_handler.get_relatorios_handler
      Description: Get reports
      Events:
        GetRelatorios:
          Type: Api
          Properties:
            RestApiId: !Ref RelatorioApi
            Path: /reports
            Method: GET

  # === HEALTH CHECK (público) ===
  HealthCheckFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: handlers.relatorio_handler.health_check_handler
      Description: Health check endpoint
      Events:
        HealthCheck:
          Type: Api
          Properties:
            RestApiId: !Ref RelatorioApi
            Path: /health
            Method: GET
            Auth:
              Authorizer: NONE

Outputs:
  RelatorioApiUrl:
    Description: "API Gateway endpoint URL for Relatório service"
    Value: !Sub "https://${RelatorioApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
    Export:
      Name: !Sub "${Environment}-relatorio-api-url"

  GetRelatoriosFunctionName:
    Description: "Get Relatórios Function Name"
    Value: !Ref GetRelatoriosFunction
    Export:
      Name: !Sub "${Environment}-get-relatorios-function"
